/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 25, 2018 at 11:24:17 PM Eastern European Standard Time
* Operating System: Version 11.1.2 (Build 15B202)
* Image Source: /System/Library/PrivateFrameworks/ToneLibrary.framework/ToneLibrary
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class TLSystemSound, NSURL;

@interface TLAlertTone : NSObject {

	unsigned _actualSoundID;
	unsigned _previewSoundID;
	TLSystemSound* _actualSound;
	TLSystemSound* _previewSound;
	NSURL* _soundFileURL;

}

@property (nonatomic,readonly) NSURL * soundFileURL;                      //@synthesize soundFileURL=_soundFileURL - In the implementation block
@property (nonatomic,readonly) TLSystemSound * actualSound; 
@property (nonatomic,readonly) TLSystemSound * previewSound; 
-(id)initWithSoundFileURL:(id)arg1 actualSoundID:(unsigned)arg2 previewSoundID:(unsigned)arg3 ;
-(TLSystemSound *)actualSound;
-(NSURL *)soundFileURL;
-(TLSystemSound *)previewSound;
@end

